language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run coverage

after_script:
  - npm run build

# Send coverage data to Coveralls
after_script: 'cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  on:
    tags: true
