language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run coverage

# Send coverage data to Coveralls
after_script: 
  'cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'
  - npm run build

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  on:
    tags: true
